-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.markers
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    email character varying COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    lat numeric NOT NULL,
    lng numeric NOT NULL,
    CONSTRAINT markers_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.markers
    OWNER to postgres;

ALTER TABLE IF EXISTS public.markers
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.markers TO anon;

GRANT ALL ON TABLE public.markers TO authenticated;

GRANT ALL ON TABLE public.markers TO postgres;

GRANT ALL ON TABLE public.markers TO service_role;

COMMENT ON TABLE public.markers
    IS 'Collection of markers to display in the map';
